# Generated by Django 5.0 on 2024-01-21 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activate_key',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ключ активации'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='активен'),
        ),
    ]
