# Generated by Django 5.0 on 2024-01-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_activate_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='activate_key',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ключ активации'),
        ),
    ]
