# Generated by Django 5.0 on 2024-01-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Опубликовать продукт')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
