# Generated by Django 5.0 on 2024-01-25 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Опубликовать продукт'), ('change_category', 'Изменить категорию')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
