# Generated by Django 5.0 on 2024-01-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'Опубликовать продукт'), ('edit_category', 'Изменить категорию'), ('edit_description', 'Изменить описание')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
