# Generated by Django 5.0 on 2023-12-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecord',
            name='viewed',
            field=models.IntegerField(null=True),
        ),
    ]
