# Generated by Django 5.0 on 2024-01-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogrecord',
            name='published',
        ),
        migrations.RemoveField(
            model_name='blogrecord',
            name='viewed',
        ),
        migrations.AddField(
            model_name='blogrecord',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='опубликовано'),
        ),
        migrations.AddField(
            model_name='blogrecord',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='просмотры'),
        ),
        migrations.AlterField(
            model_name='blogrecord',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='blogrecord',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='содержимое'),
        ),
        migrations.AlterField(
            model_name='blogrecord',
            name='title',
            field=models.CharField(max_length=150, verbose_name='название'),
        ),
    ]
