# Generated by Django 5.0 on 2023-12-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_alter_blogrecord_published_alter_blogrecord_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecord',
            name='viewed',
            field=models.IntegerField(null=True),
        ),
    ]
