# Generated by Django 5.0 on 2023-12-27 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_blogrecord_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogrecord',
            old_name='published',
            new_name='is_published',
        ),
    ]
