# Generated by Django 5.0 on 2024-01-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_alter_blogrecord_is_published_alter_blogrecord_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogrecord',
            old_name='viewed',
            new_name='view_count',
        ),
    ]
